# Generated by Django 5.0.4 on 2024-05-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikujudge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haiku',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
